pub mod arch;
pub mod cache;
pub mod cas;
pub mod cgroup;
pub mod changelog;
pub mod completion;
pub mod config;
pub mod database;
pub mod declarative;
pub mod graph;
pub mod history;
pub mod integrity;
pub mod lifecycle;
pub mod manifest;
pub mod package;
pub mod plugin;
pub mod profiler;
pub mod repo;
pub mod rollback;
pub mod security;
pub mod solver;
pub mod transaction;
pub mod update;
pub mod vendor;
pub mod sudo;
pub mod workspace;

pub use database as db;

pub use arch::{Architecture, host_architecture};
pub use cache::CacheManager;
pub use cas::CasStore;
pub use cgroup::CgroupController;
pub use changelog::ChangelogManager;
pub use completion::CompletionEngine;
pub use config::{ConfigManager, MappedConfig, CalibratedParams};
pub use database::Database;
pub use declarative::ProfileValidator;
pub use graph::DepGraph;
pub use history::HistoryEngine;
pub use integrity::IntegrityScanner;
pub use lifecycle::{LifecycleEngine, LifecycleEntry, LifecycleTransition, LifecycleEvent, PackageState, DependencyGraph, OrphanSet};
pub use manifest::ManifestParser;
pub use package::PackageEntity;
pub use plugin::{PluginRegistry, PluginSlot, PluginManager, ExternalPlugin, PluginManifest, PluginHook, PluginEvent, PluginResult, Fetcher, Builder, Packer, CurlFetcher, DefaultBuilder, ZstdPacker};
pub use profiler::{SystemProfile, DecisionEngine, DecisionMatrix, HeuristicVerdict, AutoHealer, NetworkProber};
pub use repo::RepositoryManager;
pub use rollback::RollbackManager;
pub use security::SecurityMonitor;
pub use solver::{DependencySolver, compute_depsig, scan_package_directory, build_dependency_graph};
pub use update::SelfUpdateManager;
pub use transaction::PackageTransaction;
pub use vendor::VendorManager;
pub use workspace::WorkspaceManager;
