use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use anyhow::{Result, Context, bail};

use crate::core::metadata::RLineMetadata;

/// Lazy-Mount & dinit Integrator
/// 
/// Provides zero RAM consumption for idle programs via:
/// 1. Socket-activated dinit services
/// 2. On-demand SquashFS mounting (microseconds)
/// 3. Automatic unmount when program exits
pub struct LazyMountEngine {
    root: PathBuf,
    dinit_dir: PathBuf,
    mount_scripts_dir: PathBuf,
}

impl LazyMountEngine {
    pub fn new<P: AsRef<Path>>(root: P) -> Self {
        let root = root.as_ref().to_path_buf();
        let dinit_dir = root.join("etc/dinit.d");
        let mount_scripts_dir = root.join("var/lib/mcx/mount-scripts");
        
        Self {
            root,
            dinit_dir,
            mount_scripts_dir,
        }
    }

    /// Initialize lazy-mount directories
    pub fn initialize(&self) -> Result<()> {
        fs::create_dir_all(&self.dinit_dir)
            .context("Failed to create dinit.d directory")?;
        fs::create_dir_all(&self.mount_scripts_dir)
            .context("Failed to create mount-scripts directory")?;
        Ok(())
    }

    /// Generate a dinit service for lazy-mounting a package
    /// 
    /// The service uses socket activation or trigger-based activation:
    /// - When triggered, MCX mounts the capsule (microseconds)
    /// - Passes execution to the program
    /// - Unmounts when program exits
    pub fn generate_mount_service(
        &self,
        meta: &RLineMetadata,
        mount_point: &str, )
     -> Result<PathBuf> {
        self.initialize()?;

        // Check if package has dinit_services in metadata
        let services = meta.services.as_ref();
        let service_names: Vec<String> = services
            .map(|s| s.clone())
            .unwrap_or_default();

        // Generate the main mount service
        let mount_service = self.generate_mount_service_impl(meta, mount_point, &service_names)?;
        
        // Generate socket activation services if needed
        let _socket_services = self.generate_socket_services(meta, mount_point, &service_names)?;

        Ok(mount_service)
    }

    /// Generate the main mount service file
    fn generate_mount_service_impl(
        &self,
        meta: &RLineMetadata,
        mount_point: &str,
        _services: &[String],
    ) -> Result<PathBuf> {
        let service_name = format!("mcx-mount-{}.dinit", meta.pkg_name);
        let service_path = self.dinit_dir.join(&service_name);

        // Get the active capsule path
        let capsule_var = format!("MCX_CAPSULE_{}", meta.pkg_name.to_uppercase().replace('-', "_"));
        
        let script = format!(
            r#"# MCX Lazy-Mount Service for {name} v{ver}
# Auto-generated by MCX for rLine 0.2.0+ compatibility
# This service mounts the capsule on-demand and unmounts when idle

type = script
daemon = false
depends-on = mcx-runtime

[service]
command = /system/bin/mcx-mount-runner {mount_point} {capsule_var}
timeout = 30

[subscription]
# Auto-unmount after 5 minutes of inactivity
type = timer
interval = 300
"#,
            name = meta.pkg_name,
            ver = meta.version,
            mount_point = mount_point,
            capsule_var = capsule_var,
        );

        fs::write(&service_path, &script)
            .with_context(|| format!("Failed to write lazy-mount service for {}", meta.pkg_name))?;

        // Make executable
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(&service_path, fs::Permissions::from_mode(0o755))?;
        }

        Ok(service_path)
    }

    /// Generate socket activation services for dinit_services
    fn generate_socket_services(
        &self,
        meta: &RLineMetadata,
        mount_point: &str,
        services: &[String],
    ) -> Result<Vec<PathBuf>> {
        let mut created = Vec::new();

        for service in services {
            let socket_name = format!("{}.socket", service);
            let socket_path = self.dinit_dir.join(&socket_name);

            let script = format!(
                r#"# MCX Socket Activation for {service} in {pkg}
type = socket
socket-type = stream
listen = /run/{pkg}/{service}.sock
user = {pkg}
group = {pkg}

[service]
type = script
command = /system/bin/mcx-socket-runner {mount_point} {service}
oneshot = false
"#,
                service = service,
                pkg = meta.pkg_name,
                mount_point = mount_point,
            );

            fs::write(&socket_path, &script)
                .with_context(|| format!("Failed to write socket service for {}", service))?;

            created.push(socket_path);
        }

        Ok(created)
    }

    /// Generate a mount runner script
    /// This script is called by dinit to mount the capsule and run the program
    pub fn generate_mount_runner(&self) -> Result<PathBuf> {
        let runner_path = self.root.join("system/bin/mcx-mount-runner");
        
        if let Some(parent) = runner_path.parent() {
            fs::create_dir_all(parent)?;
        }

        let script = r#"#!/bin/sh
# MCX Mount Runner
# Mounts capsule, runs program, unmounts on exit

MOUNT_POINT="$1"
CAPSULE_VAR="$2"

# Get capsule path from environment
CAPSULE_PATH="${!CAPSULE_VAR}"

if [ -z "$CAPSULE_PATH" ] || [ ! -f "$CAPSULE_PATH" ]; then
    echo "MCX: Capsule not found: $CAPSULE_PATH" >&2
    exit 1
fi

# Mount the capsule (microseconds)
/system/bin/mcx-mount "$CAPSULE_PATH" "$MOUNT_POINT" 2>/dev/null
if [ $? -ne 0 ]; then
    echo "MCX: Failed to mount capsule" >&2
    exit 1
fi

# Trap exit to ensure unmount
trap '/system/bin/mcx-umount "$MOUNT_POINT" 2>/dev/null' EXIT

# Execute the command passed as remaining arguments
shift 2
exec "$@"
"#;

        fs::write(&runner_path, script)?;
        
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(&runner_path, fs::Permissions::from_mode(0o755))?;
        }

        Ok(runner_path)
    }

    /// Remove lazy-mount service for a package
    pub fn remove_lazy_mount_service(&self, pkg_name: &str) -> Result<()> {
        let service_file = self.dinit_dir.join(format!("mcx-mount-{}.dinit", pkg_name));
        if service_file.exists() {
            fs::remove_file(&service_file)?;
        }

        // Remove socket services
        for entry in fs::read_dir(&self.dinit_dir)? {
            let entry = entry?;
            let name = entry.file_name().to_str().unwrap_or("").to_string();
            if name.starts_with(pkg_name) && name.ends_with(".socket") {
                fs::remove_file(entry.path())?;
            }
        }

        Ok(())
    }

    /// Check if a package has lazy-mount enabled
    pub fn has_lazy_mount(&self, pkg_name: &str) -> Result<bool> {
        let service_file = self.dinit_dir.join(format!("mcx-mount-{}.dinit", pkg_name));
        Ok(service_file.exists())
    }

    /// Mount a capsule (called by mount runner)
    pub fn mount_capsule(&self, capsule_path: &Path, mount_point: &str) -> Result<()> {
        fs::create_dir_all(mount_point)?;

        let status = Command::new("mount")
            .arg("-t")
            .arg("squashfs")
            .arg("-o")
            .arg("ro")
            .arg(capsule_path)
            .arg(mount_point)
            .status()
            .context("Failed to mount SquashFS capsule")?;

        if !status.success() {
            bail!("SquashFS mount failed for {:?}", capsule_path);
        }

        Ok(())
    }

    /// Unmount a capsule (called by mount runner on exit)
    pub fn unmount_capsule(mount_point: &str) -> Result<()> {
        let status = Command::new("umount")
            .arg(mount_point)
            .status()
            .context("Failed to unmount capsule")?;

        if !status.success() {
            bail!("Failed to unmount {}", mount_point);
        }

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::env;

    #[test]
    fn test_lazy_mount_structure() {
        let temp = env::temp_dir().join("test_mcx_lazy");
        let _ = fs::remove_dir_all(&temp);
        fs::create_dir_all(&temp).unwrap();

        let engine = LazyMountEngine::new(&temp);
        engine.initialize().unwrap();

        assert!(temp.join("etc/dinit.d").exists());
        assert!(temp.join("var/lib/mcx/mount-scripts").exists());

        let _ = fs::remove_dir_all(&temp);
    }
}